{
 "title": "Smart Irrigation System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Single Sensor Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Soil Moisture Tension",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(timestamp, interval 4 hour) AS \"time\",\n  soilValue\nFROM soilMoisture\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature in Celsius",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(timestamp, INTERVAL 4 hour) AS \"time\",\n  tempValue\nFROM temperature\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Tap Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(timestamp, interval 4 hour) AS \"time\",\n  intensity\nFROM tap\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "description": "0 if SUNNY, 1 if RAINING",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(timestamp, interval 4 hour) AS \"time\",\n  isRaining\nFROM rain\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Water Level Aquifer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\ndate_add(timestamp, interval 4 hour) AS \"time\",\nwaterLevel\nFROM waterLevelAquifer\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Water Level Reservoir",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\ndate_add(timestamp, interval 4 hour) AS \"time\",\nwaterLevel\nFROM waterLevelReservoir\nORDER BY timestamp"
    }
   ]
  }
 ]
}