#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define LOG_LEVEL_APP LOG_LEVEL_DBG

#define UIP_CONF_TCP 1

#undef IEEE802154_CONF_PANID
#define IEEE802154_CONF_PANID 0x0010
#endif /* PROJECT_CONF_H_ */
