-- MySQL Script generated by MySQL Workbench
-- Mon Aug  9 14:25:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iot_irrigation_system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `iot_irrigation_system` ;

-- -----------------------------------------------------
-- Schema iot_irrigation_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iot_irrigation_system` DEFAULT CHARACTER SET utf8 ;
USE `iot_irrigation_system` ;

-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`rain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`rain` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`rain` (
  `idrain` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isRaining` TINYINT NOT NULL,
  PRIMARY KEY (`idrain`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`soilMoisture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`soilMoisture` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`soilMoisture` (
  `idsoilMoisture` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `soilValue` DOUBLE NOT NULL,
  PRIMARY KEY (`idsoilMoisture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`tap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`tap` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`tap` (
  `idtap` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `intensity` DOUBLE NOT NULL,
  `interval` INT NOT NULL,
  PRIMARY KEY (`idtap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`temperature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`temperature` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`temperature` (
  `idtemperature` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tempValue` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idtemperature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`waterLevelAquifer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`waterLevelAquifer` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`waterLevelAquifer` (
  `idwaterLevel` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nodeId` VARCHAR(10) NOT NULL,
  `waterLevel` DOUBLE NOT NULL,
  PRIMARY KEY (`idwaterLevel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot_irrigation_system`.`waterLevelReservoir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot_irrigation_system`.`waterLevelReservoir` ;

CREATE TABLE IF NOT EXISTS `iot_irrigation_system`.`waterLevelReservoir` (
  `idwaterLevel` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `nodeId` VARCHAR(10) NOT NULL,
  `waterLevel` DOUBLE NOT NULL,
  PRIMARY KEY (`idwaterLevel`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
